# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBtFSBUE9x4noiTTY8YVe7RbxOdX5pqA
"""

import sympy as sp

print(" T1 SISTEMAS ")
x,y,z = sp.symbols('x y z')

# Solución única
sol1 = sp.solve([x+y+z-6, 2*x-y+z-3, x+2*y-z-3],[x,y,z])
sol1b = sp.solve([2*x+y-z-1, x-y+2*z-3, 3*x+2*y+z-7],[x,y,z])
print("Solucion unica 1:", sol1)
print("Solucion unica 2:", sol1b)

# Infinitas soluciones
sol2 = sp.solve([x+y+z-3, 2*x+2*y+2*z-6, 3*x+3*y+3*z-9],[x,y,z])
sol2b = sp.solve([x+y-z-1, 2*x+2*y-2*z-2, -x-y+z+1],[x,y,z])
print("Infinitas soluciones 1:", sol2)
print("Infinitas soluciones 2:", sol2b)

# Inconsistente
sol3 = sp.solve([x+y+z-2, 2*x+2*y+2*z-5, x-y+z-1],[x,y,z])
sol3b = sp.solve([x+y-1, 2*x+2*y-3, x-y],[x,y])
print("Sistema inconsistente 1:", sol3)
print("Sistema inconsistente 2:", sol3b)


print("\n T2 DETERMINANTES")

A = sp.Matrix([[1,2,3],[0,1,4],[5,6,0]])
A2 = sp.Matrix([[2,1,0],[1,3,2],[4,0,1]])

B = sp.Matrix([[2,0,0],[0,3,0],[0,0,4]])
B2 = sp.Matrix([[5,0,0],[0,2,0],[0,0,1]])

C = sp.Matrix([[1,2,3],[4,5,6],[7,8,9]])
C2 = sp.Matrix([[2,1,3],[0,1,4],[5,2,0]])

print("Gauss 1:", A.det())
print("Gauss 2:", A2.det())

print("Diagonal 1:", B.det())
print("Diagonal 2:", B2.det())

print("Cofactores 1:", C.det())
print("Cofactores 2:", C2.det())


print(" PROPIEDADES ")

# 🔹 1. Determinante de identidad = 1
I1 = sp.eye(3)
I2 = sp.eye(2)
print("Identidad 1:", I1.det())
print("Identidad 2:", I2.det())


# 🔹 2. Intercambio de filas cambia signo
M1 = sp.Matrix([[1,2],[3,4]])
M2 = sp.Matrix([[3,4],[1,2]])
print("Intercambio 1:", M1.det(), M2.det())

M1b = sp.Matrix([[2,5],[7,1]])
M2b = sp.Matrix([[7,1],[2,5]])
print("Intercambio 2:", M1b.det(), M2b.det())


# 🔹 3. Filas iguales ⇒ det = 0
M3 = sp.Matrix([[1,2],[1,2]])
M3b = sp.Matrix([[3,4],[3,4]])
print("Filas iguales 1:", M3.det())
print("Filas iguales 2:", M3b.det())


# 🔹 4. Filas proporcionales ⇒ det = 0
M4 = sp.Matrix([[1,2],[2,4]])
M4b = sp.Matrix([[3,6],[1,2]])
print("Proporcional 1:", M4.det())
print("Proporcional 2:", M4b.det())


# 🔹 5. Factor común en una fila
M5 = sp.Matrix([[2,4],[6,8]])
M5b = sp.Matrix([[3,6],[9,12]])
print("Factor comun 1:", M5.det())
print("Factor comun 2:", M5b.det())


# 🔹 6. Suma de filas no cambia determinante
M6 = sp.Matrix([[1,2],[3,4]])
M6_mod = M6.copy()
M6_mod[1,:] = M6_mod[1,:] + M6_mod[0,:]
print("Suma filas 1:", M6.det(), M6_mod.det())

M6b = sp.Matrix([[2,1],[5,3]])
M6b_mod = M6b.copy()
M6b_mod[1,:] = M6b_mod[1,:] + M6b_mod[0,:]
print("Suma filas 2:", M6b.det(), M6b_mod.det())


# 🔹 7. Matriz triangular → producto diagonal
T1 = sp.Matrix([[2,1,3],[0,5,4],[0,0,6]])
T2 = sp.Matrix([[3,2,1],[0,4,5],[0,0,2]])
print("Triangular 1:", T1.det())
print("Triangular 2:", T2.det())


# 🔹 8. det(AB) = det(A)*det(B)
A = sp.Matrix([[1,2],[3,4]])
B = sp.Matrix([[2,0],[1,2]])
print("Producto 1:", (A*B).det(), A.det()*B.det())

A2 = sp.Matrix([[2,1],[0,3]])
B2 = sp.Matrix([[1,4],[2,5]])
print("Producto 2:", (A2*B2).det(), A2.det()*B2.det())


# 🔹 9. det(A^T) = det(A)
M9 = sp.Matrix([[1,2],[3,4]])
M9b = sp.Matrix([[2,5],[7,1]])
print("Transpuesta 1:", M9.det(), M9.T.det())
print("Transpuesta 2:", M9b.det(), M9b.T.det())